services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: revops_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  ml_service:
    build: ./ml_service
    ports:
      - "5001:5000"
volumes:
  dbdata: