services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gtm_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=revops_db
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/test"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: postgres:14
    container_name: gtm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: revops_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d revops_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  ml_service:
    build: ./ml_service
    container_name: gtm_ml_service
    restart: unless-stopped
    ports:
      - "5001:5000"
    depends_on:
      - backend
volumes:
  dbdata: